FROM node:18-alpine as build-deps

WORKDIR /app
COPY . .
RUN npm install 
RUN  npm run build

FROM nginx:1.19-alpine

COPY ./nginx/default.conf /etc/nginx/templates/

COPY --from=build-deps /app/build /usr/share/nginx/html/

EXPOSE 5001