version: '3.8'

services:
    mysqldb:
      image: daniela9997/finance-bdd:v1.0
      env_file: ./.env
      environment: 
        - MYSQL_ROOT_PASSWORD=$MYSQLDB_PASSWORD
        - MYSQL_DATABASE=$MYSQLDB_DATABASE
      ports:
        - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT

    app:
      build: .
      image: daniela9997/finance-back:v1.0
      depends_on:
        - mysqldb
      links:
        - mysqldb
      ports:
        - 8000:8000
